repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Última versão estável
    hooks:
      - id: trailing-whitespace  # Remove espaços em branco no final das linhas
      - id: end-of-file-fixer    # Garante uma linha vazia no final dos arquivos
      - id: check-yaml           # Verifica a validade de arquivos YAML
      - id: check-json           # Verifica a validade de arquivos JSON
      - id: debug-statements     # Proíbe uso de `print()` e `pdb` em arquivos Python
      - id: check-merge-conflict # Verifica se há conflitos de merge não resolvidos

  - repo: https://github.com/psf/black  # Usando o repositório oficial do black
    rev: 24.10.0
    hooks:
      - id: black  # Formata automaticamente o código Python

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8  # Identifica problemas de linting no código Python

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort  # Organiza automaticamente os imports em arquivos Python

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
      - id: bandit  # Identifica vulnerabilidades de segurança no código Python

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.28.0
    hooks:
      - id: commitizen  # Garante que as mensagens de commit sigam um padrão semântico

  #- repo: https://github.com/pre-commit/mirrors-block
  #  rev: v0.2.2
  #  hooks:
  #    - id: block  # Bloqueia commits de certas palavras ou padrões no código
