repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace  # Remove espaços em branco no final das linhas
      - id: end-of-file-fixer   # Garante uma linha vazia no final dos arquivos
      - id: check-added-large-files  # Verifica se há arquivos grandes sendo adicionados

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black  # Formata código Python
